### ISSUE TITLE
Clicking desktop push notification potentially opens a new GBFRaiders tab

### ISSUE THREAD

**Issue by godwinskye** [ypinskiy/GBF-Raiders#39]
Upon clicking desktop notifications, sometimes it fails to copy the raid number and it instead opens a new GBFRaiders tab/page. 

Chrome Version: 74.0.3729.131
OS: Windows 10

I have attached 3 screenshots of what happens in the Console log and upon setting a breakpoint on exception.

If more info is needed, I shall provide it to the best of my ability, as I am able to reproduce it quite easily by simply clicking desktop notifications over and over.

If this is intended behavior due to a problem with the raid or anything, then I apologize for being unaware of this.

![screen1](https://user-images.githubusercontent.com/22907441/57577114-e4eea300-7424-11e9-84f5-a348a0fb4cb7.png)
![screen2](https://user-images.githubusercontent.com/22907441/57577115-e4eea300-7424-11e9-91cd-e6340522adaf.png)
![screen3](https://user-images.githubusercontent.com/22907441/57577116-e5873980-7424-11e9-93a7-e21000081776.png)

**Comment by ypinskiy** [comment]
The errors are unrelated to desktop notifications.

The notifications opening new tabs are a known issue in Chrome: [here is one example](https://bugs.chromium.org/p/chromium/issues/detail?id=898486).

Making sure your Chrome is up to date is the only thing that could help, otherwise it will need to be fixed by Chrome.
